### ISSUE TITLE
Suspected Typo in Precharge - How to modify this design

### ISSUE THREAD

**Issue by bazmn** [michaelruppe/FSAE#10]
@michaelruppe Hi Mate,

Under michaelruppe/FSAE/tree/master/Precharge#how-to-modify-this-design

You reference the need to change the 'Precharge Resistor R49.' 

I don't believe you were referencing R49 but instead R46. I don't see a need to modify R49. 

Instead R46 is the HS25 series resistor like you reference.

**Comment by michaelruppe** [comment]
Fixed!
