### ISSUE TITLE
Documentation for our team

### ISSUE THREAD

**Issue by jfulreader64** [michaelruppe/FSAE#11]
Hello,
Our TSAL design uses your schematic and just have replaced the MOSFETs in the circuit. I am documenting all our circuits and am wondering if you are okay with me posting our tsal pcb and linking to your channel and github. Your video was very informative and taught me a lot about electronics.  The readme and schematic will note that it is your design if you are okay with this!
Thanks,
John 
Clarkson Formula Electric knights

**Comment by michaelruppe** [comment]
Of course! This is an open source project and MIT licensed. All the videos are accessible in the public domain and can be linked/embedded as you like.
Glad you found it useful :v:
