### ISSUE TITLE
Comparator getting too hot

### ISSUE THREAD

**Issue by 10120860nQ50** [michaelruppe/FSAE#12]
Our schematic for our TSAL for our FSAE team is attached to this, our issue is that the comparator gets too hot when testing the board, the green LED turns on at first then stops when the comparator gets hot, and the red LED doesn't turn on or flash at all. None of us can figure out what the issue with this is
<img width="483" alt="Screen Shot 2024-03-03 at 4 37 03 PM" src="https://github.com/michaelruppe/FSAE/assets/162063860/d12ce438-213e-4575-acaa-0a145ef88ee8">
<img width="512" alt="Screen Shot 2024-03-03 at 4 37 12 PM" src="https://github.com/michaelruppe/FSAE/assets/162063860/22d12473-d8c1-4c9c-a0b0-6f79c71f5904">

**Comment by michaelruppe** [comment]
Hi! This all looks about right.
I should say that I didn't populate R12 positive feedback resistor in my design since hysteresis is not really important and I thought it might make things more complicated.
Perhaps that's the case here? Or the comparator was damaged during commissioning or testing from an errant short?
Want to post some close up shots of your hardware version? It may be a soldering issue

**Comment by 10120860nQ50** [comment]
![tempImageMsHXmh](https://github.com/michaelruppe/FSAE/assets/162063860/6650017b-b530-4120-82b1-fb60b18a8f96)

This is what our board looks like with everything soldered on

**Comment by michaelruppe** [comment]
Have you already replaced the comparator? It could have just been destroyed by an earlier mistake that had already been resolved. It looks like there could be some risk of solder bridging some pins now - perhaps in the past there was a dead short on the output

**Comment by michaelruppe** [comment]
Sanity check that the comparator is the right way around too - I can't tell from the photo if it is placed in the correct orientation

**Comment by 10120860nQ50** [comment]
Yes, the comparator was upside down at first so we took it off and soldered on a new one, but we were still running into the same issue of it getting too hot

**Comment by michaelruppe** [comment]
I'm not sure what else I can comment on aside from general debugging help.
- Probe your net voltages to check they make sense
- check for shorts between pins. There is a fair amount of solder whiskers littering the board, especially around the comparator.
- if the comparator gets hot, it's almost certainly destroyed. Remove it and measure net voltages, clear shorts, try again.

Do you understand how the circuit ought to operate well enough from the video? Removing the comparator you should be able to test the important voltages on the comparator inputs. You can also drive the output manually to check the output circuit works as intended.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
