### ISSUE TITLE
Pre-charger / Dis-charger 

### ISSUE THREAD

**Issue by DavidDast** [michaelruppe/FSAE#5]
Hi, Michael, I'm a student at a university in Sweden where I got the task to make the pre-charger 
I made this in google in drive: https://docs.google.com/spreadsheets/d/1Iv6vfXVOTpihR3HI_DqoE699ijv5pMhWjXgmG9TUZTQ/edit?usp=sharing

The issue is what kind of circuit do use and what other components do I need? 
I need some guidance.

kind regards David.

**Comment by DavidDast** [comment]
Or do you have any recommendation where to buy the circuit board

**Comment by michaelruppe** [comment]
Hi David, I can't access your link.
If you're looking for a pcb manufacturer there are plenty of options for small scale: JLC Pcb,  Pcbway etc

**Comment by michaelruppe** [comment]
If its the first precharge for your team, I'd go with a simple timer-based one.

**Comment by DavidDast** [comment]
oh sorry here is the working link:
https://docs.google.com/spreadsheets/d/1Iv6vfXVOTpihR3HI_DqoE699ijv5pMhWjXgmG9TUZTQ/edit?usp=sharing

Yes, it is the first time we build it, and not so familiar with building circuits but in the link, I have the parts that I think we need.

**Comment by DavidDast** [comment]
I also have a problem to find a company that has a capacitance of 12000uF and over 111V and that only sell in small amounts do you know a company that I can order from?

**Comment by DavidDast** [comment]
Sorry for the spam of Questions, but what did you use to download the code to the circuit?

**Comment by michaelruppe** [comment]
> Sorry for the spam of Questions, but what did you use to download the code to the circuit?

The hardware is a Teensy 4.0.
PJRC has a guide on using Teensy with the arduino IDE.

> I also have a problem to find a company that has a capacitance of 12000uF and over 111V and that only sell in small amounts do you know a company that I can order from?

I don't. Why do you need to buy this capacitor? Do your motor drivers not come with integrated capacitors?

**Comment by DavidDast** [comment]
Yes we have but they are at 100uF and we have hub motors I don't know if that changes anything? is it enough to just use one of the motor's capacitor at 1000uF and then just ramp up the resistor? 

But it seems a bit strange to have a cable go from the pre-charger to one of the hub motors that are placed near the wheel and then back to the pre-charger? then just having a capacitor in the circuit board.. just wondering

**Comment by DavidDast** [comment]
Oh sorry, now I understand I feel so dumb, yes we can connect them to the motor controllers with their capacitors.

**Comment by michaelruppe** [comment]
I'm a little confused - help me understand.
Your motor drivers already have (presumably sufficient) capacitance at their power input. Have you determined they need additional capacitance? Is that where the figure 12000uF is coming from? 
I'm afraid I can't be much help at the moment. 

What is your current working idea? Perhaps a drawing/schematic would help.

**Comment by DavidDast** [comment]
Sorry for the confusement we found that the motor controllers had 2616uF each and what we are thinking about is connecting the 2 motor controllers capacitors and use them so together we have 5230uF, so we calculated that it would take 2.6s to pre-charge to 95% 

The schematic we have for pre-charge and dis-charge

![128919283_382197646391076_1832739486696846799_n](https://user-images.githubusercontent.com/74022491/100641964-7475e280-3338-11eb-8591-09cb4759946d.png)

**Comment by DavidDast** [comment]
The 12V system is actually one system but in the schematic its two parts

**Comment by DavidDast** [comment]
I updated the excel drive link also
