### ISSUE TITLE
TSAL V3 

### ISSUE THREAD

**Issue by Dmat10** [michaelruppe/FSAE#7]
Hi Michael, 

I hope you are doing well. I am an FSAE student in Canada, and our team is currently in need of a TSAL board. Unfortunately, the member responsible for the design of the TSAL is no longer with us and left little documentation for us to pick up from. I came across your TSAL walkthrough video, and I would like to ask we could implement your TSAL V3 design for our vehicle with due credits, of course. I would appreciate your response. 

Thank you.

**Comment by michaelruppe** [comment]
Of course! This whole repo is MIT licensed - you're free to remix and reuse anything as you see fit.
Best of luck!
